version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jobapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobappuser
      POSTGRES_PASSWORD: jobapppassword
      POSTGRES_DB: jobappdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: jobapp_redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  pgdata:
