export * from './IUsersRepository';
export * from './ICompaniesRepository';
export * from './ICitiesRepository';
export * from './IResumesRepository';
export * from './IJobAdsRepository';
export * from './IApplicationsRepository';
export * from './IJobTagsRepository';
export * from './ITagsRepository';
export * from './ISearchRepository';
